# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Ant Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #Set up the Node.js 20
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        node-version: '20'
    #List the Contents of the file for debugging
    - name: List contents
      run: ls  
    #Installs the dependencies specified in package.json
    - name: Install dependencies
      run: npm install
    #Build the Project
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

      
